#!/usr/bin/env bash

ROOT=$PWD

MIX="MIX"
HAS_MIX=false

if [ -x "$(command -v mix)" ]; then
    HAS_MIX=true
fi

EXFILES=$(git status --porcelain | grep -e '^[AM]\(.*\).exs*$')

if test -z "$EXFILES"
then
    true
elif $MIX
then
    mix format
else
    echo ""
    echo "Please install php-cs-fixer globally, e.g.:"
    echo ""
    echo "Or remove ./git/hooks/pre-commit."
    echo ""
    exit 1;
fi
